### ISSUE TITLE
[fmu_copy_revision] skips empty folders

### ISSUE THREAD

**Issue by berland** [equinor/subscript#428]
The new fmu_copy_revision (python) will not copy over empty directories, whereas the perl version does.

This has not yet been reported by users, but might be a problem some day?

**Comment by asnyv** [comment]
This is an issue. Typical scenario seen with users, step by step:
1) New revision is created by copying last revision or someone overwrites the revision with an updated user copy -> folders like `rms/output` are kept, but files are not copied.
2) The workflow is **not** run from start to end in the "main branch" for the revision
3) user takes copy of "main branch". Folders like `rms/output` are now empty from where you copy from, and therefore not kept at all in the new user copy.
4) Workflow in user copy fails due to errors when trying to write to files in missing folders.
