### ISSUE TITLE
Missing dependency for module Promise

### ISSUE THREAD

**Issue by Aleksander-Karlsson** [equinor/subscript#456]
With the updated graphene package it does no longer import the promise package as a dependency, ref issue https://github.com/graphql-python/graphene/issues/1260. This breaks the Travis CI.

Suggestions:
1. Wait for graphene to fix the issue
2. Temporarily add promise to dependency in Travis / actions
3. Temporarily add promise to setup.py

**Comment by berland** [comment]
Wrong URL? 404.

**Comment by berland** [comment]
Graphene is pulled in via the ert -> ert-storage dependency chain. ert-storage pins graphene to below 3.0.0 in order to circumvent this, and a new pip version might be able to pick package versions correctly such that this problem does not appear. Can you try ensuring `pip` is upgraded before it pulls in the subscript dependencies?

**Comment by alifbe** [comment]
@berland It seems that this issue is preventing us from passing the test in github action. Will there be a fix for it? I am hoping to create a PR but most likely will not pass the test

**Comment by berland** [comment]
I do not know when there will be a new maintainer assigned to subscript by Equinor Toolbox.

The problem with `promise`  is through the `ert` dependencies, and I think it will disappear when `ert` 2.30 is released.

**Comment by alifbe** [comment]
Resolved
