### ISSUE TITLE
pack_sim issues with none UTF files

### ISSUE THREAD

**Issue by RezaeiDoust** [equinor/subscript#537]
if any Norwegian letters is present in the DATA file ( like a comment on any lines explaining anything in Norwegian), the code exits with an error message.

Solutions:
1. to make the code with any file type
2. have a temporary copy of the DATA file in UTF and then delete it afterwards.

**Comment by alifbe** [comment]
Referring to offline discussion and internal [yammer ](https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjE4MjU3Mzg0ODQ5NDA4MCJ9)post, apparently, the file is encoded using ISO-8859-1 instead of UTF-8. It's probably remains from old Unix text editor.

Two possible solutions:
1. Support ISO-8859-1 encoding in pack_sim
2. Give a warning when the file is using non utf-8 encoding and probably a hint on how to convert it

**Comment by RezaeiDoust** [comment]
As it is reported before if any of the files (DATA or INCLUDE ) have sm³ (mainly reported within VFP files)the whole pack_sim exits with an error. I hope this can be fixed.

in large models it is very tedious to go within files, find and fix it one by one.

**Comment by mferrera** [comment]
Understood, thanks for raising this again. We can take a look and see what the options are.

**Comment by HodjatMoradi** [comment]
I'm experiencing a similar problem in Gudrun when attempting to pack multiple ensembles. In my case It appears that the issue is originating from a software called Prosper which is resulting in problems with sub and superscript formatting such as **_sm<sup>3</sup>_** or **_CO<sub>2</sub>_** . If the problem is limited to these types of formatting, it may be feasible to provide support for them. As Ali mentioned, it can be a tedious task to go through numerous large files and attempt to fix them.

**Comment by mferrera** [comment]
We have fixed this so that it can read these files naturally. We'll get it into the next Komodo.

**Comment by RezaeiDoust** [comment]
Thanks Matthew,
Any time lines for the updated Komodo?

**Comment by mferrera** [comment]
Updates for the next Komodo are due this Friday but testing before it is released can take anywhere from 1-3 weeks. There's never a firm timeline, but whenever the February Komodo comes out it will be in there.
